# AWS SAM CLI config file
version = 0.1

[default.global.parameters]
stack_name = "project-sam"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "project-sam"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
disable_rollback = false
region = "ap-southeast-1"
s3_prefix = "project-sam"
