AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Hello World API Gateway Stack

Parameters:
  HelloWorldFunctionArn:
    Type: String
    Description: "ARN of the HelloWorld Lambda function"

Resources:
  HelloApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: project-sam-hello-api
      StageName: Prod
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: "Hello World API"
          version: "1.0"
        paths:
          /hello:
            get:
              responses:
                "200":
                  description: "Success"
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunctionArn}/invocations"

  HelloPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloWorldFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HelloApi}/*/GET/hello"

Outputs:
  ApiUrl:
    Description: "API Gateway Execution URL for Hello World"
    Value: !Sub "https://${HelloApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
