AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Hello World API Gateway Stack

Parameters:
  HelloWorldFunctionArn:
    Type: String
    Description: "ARN of the HelloWorld Lambda function"

Resources:
  HelloHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: project-sam-hello-http-api
      ProtocolType: HTTP

  HelloIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HelloHttpApi
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      IntegrationUri: !Ref HelloWorldFunctionArn
      PayloadFormatVersion: "2.0"

  HelloRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HelloHttpApi
      RouteKey: "GET /hello"
      Target: !Sub "integrations/${HelloIntegration}"

  HelloStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HelloHttpApi
      StageName: $default
      AutoDeploy: true

  HelloPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref HelloWorldFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HelloHttpApi}/*/*/*"

Outputs:
  ApiUrl:
    Description: "API Gateway Execution URL for Hello World"
    Value: !Sub "https://${HelloHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
