AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Items API Gateway Stack

Parameters:
  CreateItemFunctionArn:
    Type: String
    Description: "ARN of the CreateItem Lambda function"
  DeleteItemFunctionArn:
    Type: String
    Description: "ARN of the DeleteItem Lambda function"

Resources:
  ItemsNativeHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: project-sam-items-http-api
      ProtocolType: HTTP

  CreateItemIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ItemsNativeHttpApi
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      IntegrationUri: !Ref CreateItemFunctionArn
      PayloadFormatVersion: "2.0"

  DeleteItemIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ItemsNativeHttpApi
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      IntegrationUri: !Ref DeleteItemFunctionArn
      PayloadFormatVersion: "2.0"

  CreateItemRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ItemsNativeHttpApi
      RouteKey: "POST /items"
      Target: !Sub "integrations/${CreateItemIntegration}"

  DeleteItemRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ItemsNativeHttpApi
      RouteKey: "DELETE /items/{id}"
      Target: !Sub "integrations/${DeleteItemIntegration}"

  ItemsStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ItemsNativeHttpApi
      StageName: $default
      AutoDeploy: true

  CreateItemPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateItemFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsNativeHttpApi}/*/*/*"

  DeleteItemPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteItemFunctionArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ItemsNativeHttpApi}/*/*/*"

Outputs:
  ApiUrl:
    Description: "API Gateway Execution URL for Items"
    Value: !Sub "https://${ItemsNativeHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
